-   id: api-checker
    name: checks for API documentation.
    description: ensures Ansible collection public API is properly documented.
    entry: api-checker
    language: python
    stages: [pre-commit, pre-push, manual]
    minimum_pre_commit_version: 3.2.0
